### ISSUE TITLE
Weekly Progress Tracking - Ali Tariq

### ISSUE THREAD

**Issue by alitariq4589** [10x-Engineers/riscv-ci-partners#1]
**August, 30 - September, 1**

- Built Jenkins from using cloned github repository instead of precompiled one.  
- Spent some reading Jenkins documentation and watching tutorials.
- Attended a team session and discussed what is big picture and future goals and initiatives.
- Created a simple Jenkins pipeline from Maven sample script in Jenkins.
- Resolved some issues encountered while creating and building the Jenkins pipelines and documented them.

> Documentation for Jenkins first sample pipeline and its pre-requisites: https://docs.google.com/document/d/1ioHGHNqlLtHFsXDVf6mDPFFoh2BLsN13nwjOhOG3EiM/edit?usp=sharing

**September, 2 - September, 8**
- Created a two stage pipeline for compiling a C file with GCC and then executing it on local directory from github.
- Compiled the github C file with RISCV GNU toolchain and executed it using spike simulator on local directory using jenkins.
- Changed the workspace to local directory and built the job.
- Locally installed packages can also be used by Jenkins.
- Managed the user security and authentication in Jenkins.
- Created a new node in Jenkins and used it to build a project on it.
- Decided to proceed with Unix user/group database for Jenkins authentication after a discussion.

**September, 9 - September, 16**
- Converted all the existing jenkins documentation to markdown. Documentation for jenkins is available at: https://github.com/10x-Engineers/riscv-ci-partners/tree/main/jenkins_docs
- PAM Authentication is applied successfully and the non sudo 'jenkins' user had to be included to shadow group.
- Added unix user/group database to jenkins.
- For some reason ubuntu 22.04 did not work properly on my machine, so had to reinstall ubuntu 20.04 again and installed jenkins in it again.
- Installed and created LXC container on ubuntu 20.04. _Documentation is available at: https://github.com/10x-Engineers/riscv-ci-partners/tree/main/jenkins_docs_
- Created a directory on LXC container and used SSH to access it in jenkins and used it as a default jenkins node. _Documentation is available at: https://github.com/10x-Engineers/riscv-ci-partners/tree/main/jenkins_docs_

- _**Unsolved Potential Vulnerabilities and Issues**_  
    - _Adding a non sudo user to shadow group makes webserver potentially vulnerable. Because it gives read access to the `/etc/shadow` which by default only root can read and write. This file contains hashes of the passwords of all the users on a linux machine. But this step is necessary for using PAM authentication on Jenkins_  

**September, 19 - September, 23**
- Created the prescript with jenkins freestyle jobs which creates new directories with date and some random number.
- Created a bash script which creates a _.vars_ file and stores the most recent directory names in it. The script checks at the start if the .vars file is present in the directory of the workspace, otherwise creates it and that file keeps track of most recent three directories. Bash script source that .vars file and then deletes all the directories older than most recent three directories and then updates the .vars file regarding the most recent files.  
- Created a second container for a second node for working with multinode pipelines.
- Created multinode pipelines with jenkins freestyle jobs, jenkins scripted jenkinsfile and also with jenkins declarative pipeline and also documented it. _The documentation is present at: https://github.com/10x-Engineers/riscv-ci-partners/blob/main/jenkins_docs/Multinode_Pipelines.md_  

- _**Unsolved Potential Vulnerabilities and Issues**_  
    - Adding a non sudo user to shadow group makes webserver potentially vulnerable. Because it gives read access to the `/etc/shadow` which, by default, only root can read and write. This file contains hashes of the passwords of all the users on a linux machine. But this step is necessary for using PAM authentication on Jenkins. 

**September, 26 - September, 30**
- Integrated github webhook with jenkins such that every push on configured GitHub repo triggers a job build. A pull request with its documentation is also created on riscv-ci-partners.
- Discussed some points with @mmoizhussain regarding what should be the job type of pre-script and what should be the job type of pipeline. Based on the discussion, proceeded with using jenkins freestyle job as prescript and jenkins native pipeline job as CI pipeline.
- Created helloworld pipeline job jenkinsfile in declarative pipeline syntax and created the pull request for it along with the scripted pipeline syntax jenkinsfile (which was created before) on riscv-ci-partners repo.
- Created another lxc container for building linux kernel for riscv with riscv64-unknown-linux-gnu-gcc toolchain. 
- Built QEMU Emulator, riscv64-linux-gnu toolchain and linux kernel on newly created lxc container.
- Encountered an issue to boot linux kernel on QEMU during execution of `/init` file.
- Learned about, what is the purpose of iptables in linux.
- Found out the fact that `mknod` command (for creating character and block oriented devices which are also called special files) cannot be used on un-privileged containers in any way. These devices are required for linux kernel for boot properly.
- Created another privileged lxc container and again cloned and built riscv toolchain, linux kernel and busybox inside it. It is done so that I may have proper permissions to build and boot linux kernel on qemu and creating its binutils to boot process.

- _**Unsolved Potential Vulnerabilities and Issues**_  
    - Adding a non sudo user to shadow group makes webserver potentially vulnerable. Because it gives read access to the `/etc/shadow` which, by default, only root can read and write. This file contains hashes of the passwords of all the users on a linux machine. But this step is necessary for using PAM authentication on Jenkins. 
  
**October, 3 - October, 7**
- Completed building Linux kernel with `riscv64-unknown-linux-gnu-gcc` and booted it on qemu in an unprivileged LXC container with busybox utilities. Copied the linux kernel image on proxmox lxc container `runnerContainer` and installed `qemu-system-riscv64` on `runnerContainer`.  Created the documentation of whole process and added to pull request.
- Configured PAM authentication security realm in Jenkins proxmox server.  
- Created a `Runner1` node on a separate LXC container (named as `runnerContainer`) and executed a `Hello world` project on it.  
- Configured push webhook with Jenkins.
- Set up jenkins read permissions for `anonymous` users (which means any user who visits the site without logging in).
- Added `spike`, `riscv64-unknown-elf-gnu-*` and `riscv-pk` binary on lxc container `runner1`.
- Created the documentation on how to make a package detectable by jenkins on a slave node and added to pull request.
- `GithubPollScm` option only works for github push events and does not work with pull requests and other events received from github. So used another plugin called `GitHub Pull Request Builder` plugin. Created its documentation and added to pull request.  
- Added the `jenkins-ci` repository to `riscv-ci-partners` repositories and transfered its ownership to `10xEngineers`.
- Corrected the shellcheck errors in the script.
- _**Unsolved Potential Vulnerabilities and Issues**_  
    - Adding a non sudo user to shadow group makes webserver potentially vulnerable. Because it gives read access to the `/etc/shadow` which, by default, only root can read and write. This file contains hashes of the passwords of all the users on a linux machine. But this step is necessary for using PAM authentication on Jenkins. 
    - Using `GitHub Pull Request Builder` plugin means that anything added in the pull request source code will run on the jenkins agent (it can also be a malicious code).  
  

  
**October, 10 - October, 14**
- Worked on Multibranch pipelines and tried to understand their working a little. They work without any source code in themselves.  
- After discussing with Moiz, it is decided that we will go with giving users the permissions to see and add credentials in jenkins and not with multibranch pipeline because it will become more complex.
- Installed mkdocs and converted all the documentation in `readthedocs` format in mkdocs.
- Deployed mkdocs documentation with gh-pages and created a pull request.
- Build python with riscv64-unknown-linux target architecture.
- Created a job for building python3.8.15 in jenkins and also created the respository on github with Python's source code
- _**Unsolved Potential Vulnerabilities and Issues**_  
    - Adding a non sudo user to shadow group makes webserver potentially vulnerable. Because it gives read access to the `/etc/shadow` which, by default, only root can read and write. This file contains hashes of the passwords of all the users on a linux machine. But this step is necessary for using PAM authentication on Jenkins. 
    - Using `GitHub Pull Request Builder` plugin means that anything added in the pull request source code will run on the jenkins agent (it can also be a malicious code). 
  
**October, 17 - October, 21**
-  Created the demo video regarding github and jenkins integration and uploaded it to slack channel.
- Built qemu for riscv as "linux-user" instead of qemu-system-riscv64 which needs a kernel image to operate. 
- Solved the dynamic linker problem with qemu-riscv64. This issue can be solved by adding `-L $RISCV_SYSROOT`. Where `$RISCV_SYSROOT` is the path to `sysroot/` folder located inside riscv linux toolchain.
- Ported `qemu-riscv64` to runner1.
- Created the helloworld job to compile on x86 as well as riscv64 (this time on `qemu-riscv64` instead of `spike`).
- Upgraded to Jenkins 2.374.
- Changed the "Contact us" in software developer's guide.
- Built git, openjdk and gcc from source for x86 and copied it to new runner. Also added riscv toolchain on it.
-  Built Python3.8.15 for riscv and run on `qemu-riscv64` in jenkins job.
- Added jenkins job to run 'BenchUtils' benchmark on riscv64 as well as x86.
- Created a job to run benchmarks with truebench.
- Built pip for riscv64 with python.
- _**Unsolved Potential Vulnerabilities and Issues**_  
    - Adding a non sudo user to shadow group makes webserver potentially vulnerable. Because it gives read access to the `/etc/shadow` which, by default, only root can read and write. This file contains hashes of the passwords of all the users on a linux machine. But this step is necessary for using PAM authentication on Jenkins. 
    - Using `GitHub Pull Request Builder` plugin means that anything added in the pull request source code will run on the jenkins agent (it can also be a malicious code).  
  
**October, 24 - October, 28**
-  Corrected formatting mistakes in riscv-ci documentation.  
- Tried to build missing optional packages for python (such as zlib, openssl) but could not succeed.  
- Built ruby for riscv64 architecture without extentions such as 1): Fiddle 2): Openssl 3): Psych 4): Readline  
- Created documentation of cross compilation, building ruby and building openssl with cross-compiler.  
- Corrected some formatting mistakes in documentation and committed them in pull request.
- Added documentation for qemu-riscv64.  
- Built coremark and dhrystone and added their documentation in the pull request.
- _**Unsolved Potential Vulnerabilities and Issues**_  
    - Adding a non sudo user to shadow group makes webserver potentially vulnerable. Because it gives read access to the `/etc/shadow` which, by default, only root can read and write. This file contains hashes of the passwords of all the users on a linux machine. But this step is necessary for using PAM authentication on Jenkins. 
    - Using `GitHub Pull Request Builder` plugin means that anything added in the pull request source code will run on the jenkins agent (it can also be a malicious code).  

**October, 31 - November, 4**
-  Tried to resolve openssl dependency issue for python but it did not work. Python still could not find openssl.
- Got TFTP access violation error from ubuntu 22.04 pre-built image for riscv64.
- Cross-compiled following linux utilities for riscv64.
m4, ncurses, bash, coreutils, diffutils, file, findutils, gawk, grep, gzip, make, patch, sed, tar, xz, binutils.
- Tried to compile gcc 12.2.0 as native compiler for riscv64 but it did not work. Also tried to tweak its file but failed to build it.
- Successfully booted ubuntu 22.04 server installation for riscv64 on qemu-system-riscv64
- _**Unsolved Potential Vulnerabilities and Issues**_  
    - Adding a non sudo user to shadow group makes webserver potentially vulnerable. Because it gives read access to the `/etc/shadow` which, by default, only root can read and write. This file contains hashes of the passwords of all the users on a linux machine. But this step is necessary for using PAM authentication on Jenkins. 
    - Using `GitHub Pull Request Builder` plugin means that anything added in the pull request source code will run on the jenkins agent (it can also be a malicious code).

**Comment by mmhus** [comment]
Closing, as this is going internal.
