### ISSUE TITLE
Future Action Items

### ISSUE THREAD

**Issue by alitariq4589** [10x-Engineers/riscv-ci-partners#15]
- [x] Need VM with more resources
- [x]  Diagram correction in presentation
- [ ] Launch updates into releases
- [x] Correcting benchmarking results
- [x] Changing documentation title from RISC-V CI to Cloud-V
- [x] Updated Cloud-V documentation for letsencrypt.
- [x] Benchmark with python, jdk, emacs, linux utilities, atom, LLVM, go ocaml, riscvgcc 
- [x] What are the other CI development tools being used now and were in the past.
- [x] Is riscv-ci using hardware for running CI Tests.
- [x] Understanding what Imperas is offering for software testing.
> Imperas has been using Continuous Integration with a build server and test automation system for over 5 years.
> Imperas uses Jenkins internally and has customers developing embedded software using Jenkins and test automation using Imperas virtual platform simulation products. See this [link](https://www.imperas.com/continuous-integration-using-jenkins-and-virtual-platforms)
- [x] Configuring CI testing environment on RISC-V board.
- [x] Currently the port is 8086 on which we are running our domain. For this we have to explicitly type `cloud-v.co:8086`. Need to find a way to host it on port 443 but also allowing HTTPS traffic to keep flowing.
- [x] List of important softwares which are ported to RISC-V.  
> A long list is available [here](https://github.com/riscvarchive/riscv-software-list)
- [ ] Need to enable more QEMUs.
- [ ] Create a cost model: How does the cost grow with compute + memory + disk.
- [x] Need to monitor resources.
- [ ] Need to create policy for cloud-v usage (guidlines).  
- [x] Create summit presentation (helpful link [here](https://www.slideshare.net/RISC-VFoundation1/riscv-software-state-of-the-union) )

**Comment by mmhus** [comment]
Update this issue, and close if necessary. @alitariq4589

**Comment by alitariq4589** [comment]
This is handled internally now
