### ISSUE TITLE
Apply for an account

### ISSUE THREAD

**Issue by jiewu-plct** [10x-Engineers/riscv-ci-partners#27]
Hi
I want to apply for an account to login https://cloud-v.co .
The following is my information:
Name：jie wu
Contact Email: wujie22@iscas.ac.cn
URL of the GitHub project repository: https://github.com/jiewu-plct/ci_test.git
Name of your organization: ISCAS

I look forward to hearing from you. Thank you!

**Comment by alitariq4589** [comment]
Hi Jie Wu,
We are very glad to see you show interest in using Cloud-V. I have emailed you the relevant information. If you have any query, please don't hesitate to contact me through email or GitHub issues.

**Comment by alitariq4589** [comment]
@jiewu-plct
Dont forget to ping me up once you have added github credentials. I need to add the added credentials in the job build. Also please send me ID of credentials via email.
