### ISSUE TITLE
Minutes of internal sync-up

### ISSUE THREAD

**Issue by alitariq4589** [10x-Engineers/riscv-ci-partners#3]
### **26-09-2022**
Takeaways for team members are as follows:

[@Moiz Hussain](https://10xengineersgroup.slack.com/team/U01T26WT5C7)

1. will setup disks on server.
2. Top level domain (TLD) for Jenkins

[@Haseeb Azaz Talib](https://10xengineersgroup.slack.com/team/U01UJEU5T5G)

1. Will do port forwarding.
2. Mount the drives set up by  [@Moiz Hussain](https://10xengineersgroup.slack.com/team/U01T26WT5C7)
4. Set up Environmental modules.
5. Enable cross compilers in environmental modules.
6. Automate the installation of environmental modules.
7. Use Ansible for script execution on multiple machines/containers at once.

[@Musharraf Hanif](https://10xengineersgroup.slack.com/team/U03HWE96ZFW)

1.  is expected to complete following tasks before 21st October:
2. Login with separate user account on server.
3. Generate binaries for environmental modules.
4. Compile Two versions of GCC RISCV compiler for compiling bare metal as well as linux (also llvm compilers but as later task).
5. Running the generated binaries on QEMU emulator.
6. Find a way to SSH to QEMU emulator instead of using GUI.
7. Manage extra storage for compilers and setup 32GB swap for llvm compiler.

[@Ali Tariq](https://10xengineersgroup.slack.com/team/U03HBJKE7U7)

1. Check if Jenkinsfile and prescript, both are supported on freestyle job as well as jenkins' native pipeline job.
2. Push the jenkins files on riscv-lab-partners repository of 10XE.
3. Manage Jenkins frontend permissions.  

**General Deadlines:**

1. A prototype of project should be ready before 30th October.
2. Last month will be reserved for creating presentation of riscv summit.
3. At the end QEMU emulator will be ready which will run linux kernel on it and will execute all the runs.  
  
### **18-10-2022**
Takeaways for internal sync-up 17-10-2022:
- First some users will be brought onboard and then libraries will be installed according to requirements of users.
- Next meeting is two weeks later untill then make some improvement to documentation and server infrastructure.
- Software developer Guide's page should be named as "Software developer onboarding guide".
- Post either on social/professional media network for potential developers.
- We will have separate nodes for testing and official builds.
- We will need 100GB storage for work.
- We will use newly created runner for jenkins and the older runner will be reserved for monitoring usage and analytics with Prometheus and Grafana.
- Takeaways for [@Bilal Zafar](https://10xengineersgroup.slack.com/team/U01RJGZUJRY)
    - Will try to get some developers from Mentor graphics for porting their "nucleus".
    - Will try to get a user whose software is not yet ported to RISC-V.
    - Will suggest some applications on python/tcl/C which should be small (simple benchmarking suite/coremark).
    - Check whether or not compliance folks need our CI testing.
- Tasks for [@Ali Tariq](https://10xengineersgroup.slack.com/team/U03HBJKE7U7)
    - Will complete the Python build along with building tcl files.
    - Will run the compiled tool on qemu.
    - Will import the cross compiler on newly created runner.
    - Will install and compile different versions of tools, version numbers need to be remembered all the time.
- Tasks for [@Haseeb Azaz Talib](https://10xengineersgroup.slack.com/team/U01UJEU5T5G)
    - Will installed packages on newly created runner.
    - Install environmental modules on newly created runner.
    - Will create a folder for cross compilers to be copied into.
- Paths suggested by [@Moiz Hussain](https://10xengineersgroup.slack.com/team/U01T26WT5C7) for building:
    - /src will be source folder.
    - Each source folder of tool will have its own $commit_hash/10xconfig directory in which configure command will be run.
    - Each software's --prefix  will be at /software/$Software_name/$commit_hash  where the compiled binaries will be installed.
    - The path for environmental modules will be /software/$Software_name/$commit_hash
- Few Suggestions from [@Bilal Zafar](https://10xengineersgroup.slack.com/team/U01RJGZUJRY):
    1. [Microbench](https://github.com/VerticalResearchGroup/microbench): very simple benchmark programs used for processor comparison in academia. Tutorial on running them in a simulator (GEM5) are available [here] (https://www.gem5.org/documentation/gem5art/tutorials/microbench-tutorial). Theoretically, these should be easy to port/compile/run on our system.
    2. [Benchutil](https://github.com/shaswata56/BenchUtil): very simple benchmark C programs. Calculate raw operations per second kind of statistics.
    3. [TrueBench](https://truebench.the-toffee-project.org/index.php?page=download&lang=en): source code is at the bottom of the page. A single C file.
    4. Replicate Renode's work on building TensorFlow Lite (https://antmicro.com/technologies/risc-v/) for RISC-V. This will be a big win if we can do it (it will be difficult, no doubt).
    5. Successful effort to porting Firefox and Chromium to RISC-V. Probably complicated and not straight forward. [Git](https://github.com/isrc-cas/chromium-v8-build), [message thread](https://lists.riscv.org/g/software/topic/83352236) with familiar names.
[Compiling](https://www.youtube.com/watch?v=Q0jHbGQY9u0) a Benchmark for RISC-V. Interestingly, Tom's Hardware guy uses building RISC-V toolchain as the benchmark!

**Comment by mmhus** [comment]
Closing. Going internal.
