### ISSUE TITLE
10xEngineers Repository Credentials

### ISSUE THREAD

**Issue by alitariq4589** [10x-Engineers/riscv-ci-partners#38]
Cloud-V requires owner credentials for triggering the jobs when a pull requested is created. As 10xEngineers owner credentials are not added in Cloud-V, so the PR events cannot be configured as trigger for builds.

**Comment by mmhus** [comment]
Known issue. Temporarily use non org repo.

**Comment by mmhus** [comment]
Closing, going internal.
