### ISSUE TITLE
Installation of xv6 OS

### ISSUE THREAD

**Issue by salmanzaffar** [10x-Engineers/riscv-ci-partners#46]
In the name of Allah, the most gracious, the dispenser of grace. 
Peace be upon Rasulullah. 

Dear 10x Guys, 

I wish to use the xv6 OS on RISC-V (64-bit) in QEMU. I hope that you can let me know if it is installable at all. Here is the link 

https://pdos.csail.mit.edu/6.828/2022/xv6.html

If you guys can confirm that it is useable on your provided setup then please make an account for me. 

regards
Salman Zaffar, PhD.

**Comment by alitariq4589** [comment]
Assalam o Alaikum @salmanzaffar ,
Thank you for approaching us for using our CI infrastructure. We are currently working on xv6 operating system as we speak. I will get back to you as soon as we are done. In the meantime, kindly spend a few moments to fill out this form https://forms.gle/BSRjWqWbB6HNNxxd9. And if you have any query you can contact us at cloud-v@10xengineers.ai

**Comment by salmanzaffar** [comment]
Any updates?
