### ISSUE TITLE
Formatting for developer guide

### ISSUE THREAD

**Issue by mmhus** [10x-Engineers/riscv-ci-partners#9]
https://10x-engineers.github.io/riscv-ci-partners/Software_Developer_Guide/ this page doesn't have proper formatting for list points, i.e. instructions should be shown as a list e.g:
- Login with provided credentials. 
- Click on the drop down near user profile as shown in image below.
instead of:
 - Login with provided credentials. - Click on the drop down near user profile as shown in image below.
 
 There are other instances of this as well. Please fix.
 
 Please also add instruction on how to get an account for jenkins with 10xEngineers (contact us by github)

**Comment by alitariq4589** [comment]
> Please also add instruction on how to get an account for jenkins with 10xEngineers (contact us by github)
What should be the mail on which the developer will contact us ?

**Comment by mmhus** [comment]
@alitariq4589 pls update an close issue if needed.

**Comment by alitariq4589** [comment]
This problem is resolved now. So I am closing this
